# Generated by Django 5.2.15 on 2026-07-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura', '0002_anonymoususer'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususer',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
