# Generated by Django 5.2.15 on 2026-07-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura', '0003_anonymoususer_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_type',
            field=models.CharField(default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
